#see https://bettercodehub.com/docs/configuration-manual#excludingfilesanddirectoriesfromanalysis and https://bettercodehub.com/docs/configuration-manual#customizingfilefiltering

#exclude:
#- /tests/.*
#- .*/FileYouWantToExclude\.php